# Generated by Django 3.2.6 on 2021-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('working_role', models.CharField(choices=[('ta', 'Taster'), ('de', 'Developer'), ('ma', 'Manager')], max_length=2)),
                ('analyst', models.CharField(max_length=122)),
                ('team', models.CharField(max_length=122)),
                ('manager', models.CharField(max_length=122)),
                ('backup_person', models.CharField(max_length=122)),
                ('job_nature', models.CharField(choices=[('fu', 'Full Time'), ('pa', 'Part Time'), ('ho', 'Hourly Basis')], max_length=2)),
                ('phone', models.CharField(max_length=122)),
            ],
        ),
    ]
